# Markdown renderer configuration
[goldmark.renderer]
unsafe = true # 一定要设成true 不然在markdown 插入的html 无效, 不能排版图片并列显示的效果

[tableOfContents]
endLevel = 4
ordered = true
startLevel = 2

[highlight]
noClasses = false
codeFences = true
guessSyntax = true
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
tabWidth = 4
